---
- name: 🚀 Aprovisionamiento de VM
  hosts: all
  gather_facts: true
  become: false
  vars:
    valid_actions:
      - validate_capacity
      - deploy_nessus
      - general_task
      - registry_vm
      - crowstrike_agent
      - minio_ansible_automation
      - vault_core
      - provisioning
      - crear_usuarios
      - install_uim_agent
      - user_management
      - awx_register
      - parchado

  pre_tasks:
    - name: 🔍 Validar que se haya definido una acción
      ansible.builtin.fail:
        msg: "Debes definir una variable 'action'. Ejemplo: -e action=deploy_nessus"
      when: action is not defined

    - name: ✅ Validar que la acción es válida
      ansible.builtin.fail:
        msg: "Acción '{{ action }}' no es válida. Opciones válidas: {{ valid_actions | join(', ') }}"
      when: action not in valid_actions

  tasks:
    # - name: 🏗️ Ejecutar Aprovisionamiento
    #   ansible.builtin.include_role:
    #     name: aprovisionamiento_instancias
    #   register: r_provisioning
    #   when: action == 'provisioning'

    - name: 🔎 Debug de todos los facts recolectados
      ansible.builtin.debug:
        var: ansible_facts
      when: action == 'provisioning'

    - name: 📤 Exportar variables del host remoto para el siguiente play
      ansible.builtin.set_stats:
        data:
          vm_hostname: "{{ ansible_hostname }}"
          vm_ip_address: "{{ ansible_all_ipv4_addresses[0] | default('127.0.0.1') }}"
          vm_ostype: "{{ ansible_os_family }}"
          vm_nics: "{{ ansible_interfaces }}"

    - name: 🧠 Consolidar conexión del host aprovisionado
      ansible.builtin.set_fact:
        connection_info:
          hostname: "{{ inventory_hostname }}"
          ip: "{{ ansible_host }}"
          os: "{{ ansible_os_family }}"
          user: "{{ ansible_user | default('root') }}"
          password: "{{ ansible_password | default('i20unix06b') }}"
          connection: "{{ ansible_connection | default('ssh') }}"
          port: "{{ ansible_port | default(22) }}"

    - name: ➕ Registrar host como dynamic_vm
      add_host:
        name: "{{ connection_info.hostname }}"
        ansible_host: "{{ connection_info.ip }}"
        groups: dynamic_vm
        ansible_user: "{{ connection_info.user }}"
        ansible_password: "{{ connection_info.password }}"
        ansible_connection: "{{ connection_info.connection }}"
        ansible_port: "{{ connection_info.port }}"

- name: 🧩 Ejecución de roles sobre la VM aprovisionada
  hosts: dynamic_vm
  gather_facts: false
  become: false

  pre_tasks:
    - name: ⚙️ Recolectar facts del sistema remoto
      ansible.builtin.setup: {}

  tasks:
    - name: ⚙️ General Tasks
      ansible.builtin.include_role:
        name: general_task
      when: action == 'general_task'

    - name: 🛡️ Deploy Nessus
      ansible.builtin.include_role:
        name: deploy_nessus
      when: action == 'deploy_nessus'

    - name: 🐦 Instalar Crowdstrike
      ansible.builtin.include_role:
        name: crowdstrike
      when: action == 'crowstrike_agent'

    - name: 👥 Crear usuarios
      ansible.builtin.include_role:
        name: crear_usuarios
      when: action == 'crear_usuarios'

    - name: 📦 Instalar UIM
      ansible.builtin.include_role:
        name: install_uim_agent
      when: action == 'install_uim_agent'

    - name: 🧾 Registrar en RCP
      ansible.builtin.include_role:
        name: rcp_register
      when: action == 'rcp_register'

    - name: 🧰 Aplicar parchado
      ansible.builtin.include_role:
        name: parchado
      when: action == 'parchado'
