---
- name: 🚀 Aprovisionamiento de VM
  hosts: localhost
  gather_facts: false
  become: false
  vars:
    valid_actions:
      - validate_capacity
      - deploy_nessus
      - general_task
      - registry_vm
      - crowstrike_agent
      - minio_ansible_automation
      - vault_core
      - provisioning
      - crear_usuarios
      - install_uim_agent
      - user_management
      - awx_register
      - parchado

  pre_tasks:
    - name: 🔍 Validar que se haya definido una acción
      ansible.builtin.fail:
        msg: "Debes definir una variable 'action'. Ejemplo: -e action=deploy_nessus"
      when: action is not defined

    - name: ✅ Validar que la acción es válida
      ansible.builtin.fail:
        msg: "Acción '{{ action }}' no es válida. Opciones válidas: {{ valid_actions | join(', ') }}"
      when: action not in valid_actions

  tasks:
    # - name: 🏗️ Ejecutar Aprovisionamiento
    #   ansible.builtin.include_role:
    #     name: aprovisionamiento_instancias
    #   register: r_provisioning
    #   when: action == 'provisioning'
    - name: 🏗️ Recoger facts de localhost
      ansible.builtin.setup:
      register: r_provisioning
      when: action == 'provisioning'

    - name: 📤 Exportar variables de localhost para pruebas
      ansible.builtin.set_stats:
        data:
          vm_hostname: "{{ r_provisioning.ansible_facts.ansible_hostname }}"
          vm_ip_address: "{{ r_provisioning.ansible_facts.ansible_default_ipv4.address }}"
          vm_ostype: "{{ r_provisioning.ansible_facts.ansible_os_family }}"
          vm_nics: "{{ r_provisioning.ansible_facts.ansible_interfaces }}"
      when: action == 'provisioning'

    - name: ➕ Registrar localhost como dynamic_vm para pruebas
      add_host:
        name: "{{ r_provisioning.ansible_facts.ansible_hostname }}"
        ansible_host: "{{ r_provisioning.ansible_facts.ansible_default_ipv4.address }}"
        groups: dynamic_vm
        ansible_user: "root"
        ansible_password: "i20unix06b"
        ansible_connection: "ssh"
        ansible_port: 22
      when: action == 'provisioning'

- name: 🧩 Ejecución de roles sobre la VM aprovisionada
  hosts: dynamic_vm
  gather_facts: true
  become: false

  tasks:
    - name: ⚙️ General Tasks
      ansible.builtin.include_role:
        name: general_task
      when: action == 'general_task'

    - name: 🛡️ Deploy Nessus
      ansible.builtin.include_role:
        name: deploy_nessus
      when: action == 'deploy_nessus'

    - name: 🐦 Instalar Crowdstrike
      ansible.builtin.include_role:
        name: crowdstrike
      when: action == 'crowstrike_agent'

    - name: 👥 Crear usuarios
      ansible.builtin.include_role:
        name: crear_usuarios
      when: action == 'crear_usuarios'

    - name: 📦 Instalar UIM
      ansible.builtin.include_role:
        name: install_uim_agent
      when: action == 'install_uim_agent'

    - name: 🧾 Registrar en RCP
      ansible.builtin.include_role:
        name: rcp_register
      when: action == 'rcp_register'

    - name: 🧰 Aplicar parchado
      ansible.builtin.include_role:
        name: parchado
      when: action == 'parchado'
