---
- name: Running update_all/rcp_all on host - update & upgrade
  block:

    - name:
        Running update_all/rcp_all - version 7 and below  # noqa package-latest
      ansible.builtin.yum:
        name: '*'
        state: latest
        exclude: "{{ yum_exclude_patch_list }}"
        update_cache: true
        lock_timeout: 180
        enablerepo: "{{ enable_repo }}"
        disablerepo: "{{ disable_repo }}"
        disable_gpg_check: "{{ disable_gpg_check }}"
      register: yum_update_rcp_result
      async: "{{ async_value }}"
      poll: "{{ poll_value }}"
      when:
        - not run_pre_patch_steps
        - ansible_distribution_major_version | int < 8
      ignore_errors: true

    - name:
        Running update_all/rcp_all - version 8 and above  # noqa package-latest
      ansible.builtin.dnf:
        name: '*'
        state: latest
        exclude: "{{ yum_exclude_patch_list }}"
        update_cache: true
        lock_timeout: 180
        enablerepo: "{{ enable_repo }}"
        disablerepo: "{{ disable_repo }}"
        disable_gpg_check: "{{ disable_gpg_check }}"
      register: dnf_update_rcp_result
      async: "{{ async_value }}"
      poll: "{{ poll_value }}"
      when:
        - not run_pre_patch_steps
        - ansible_distribution_major_version | int >= 8
      ignore_errors: true

    - name: Running update_all/rcp_all - in case of issues with yum module
      ansible.builtin.command: yum -y update -x '{{ yum_exclude_patch_list }}'
      register: patching_result
      async: "{{ async_value }}"
      poll: "{{ poll_value }}"
      changed_when: true
      args:
        warn: false
      when: run_pre_patch_steps
      ignore_errors: true

    - name: Set patching result
      ansible.builtin.set_fact:
        update_rcp_result:
          "{% if yum_update_rcp_result is not skipped
          %}{{ yum_update_rcp_result }}{%
          elif dnf_update_rcp_result is not skipped
          %}{{ dnf_update_rcp_result }}{% else %}{{ patching_result
          }}{% endif %}"

    - name: Fail the execution
      ansible.builtin.fail:
        msg: "Failed to run update_all/rcp_all patching"
      when: update_rcp_result is failed

  rescue:

    - name:
        Retry patching in case of yum lock
        issue  # noqa command-instead-of-module
      ansible.builtin.command: yum -y update -x '{{ yum_exclude_patch_list }}'
      when:
        - not run_pre_patch_steps
        - "'yum lockfile is held by another process' in update_rcp_result.msg"
      register: retry_update_rcp_result
      failed_when: false
      async: "{{ async_value }}"
      poll: "{{ poll_value }}"
      changed_when: true

    - name: Return code incase of redhat update_all or rcp_all fails
      when:
        (update_rcp_result is failed and
        retry_update_rcp_result is skipped) or
        (retry_update_rcp_result is not skipped and
        retry_update_rcp_result.rc != 0)
      block:

        - name: Return code incase of redhat update_all fails - module
          when: not run_pre_patch_steps
          ansible.builtin.include_role:
            name: returncode
          vars:
            rc_support: "developer"
            rc_group: "component_playbook"
            rc_number: 5009
            rc_message:
              "Redhat update_all or rcp_all patching failed.
              Below is the error:
              {{ update_rcp_result.msg }}"

        - name: Return code incase of redhat update_all fails - command
          when: run_pre_patch_steps
          ansible.builtin.include_role:
            name: returncode
          vars:
            rc_support: "developer"
            rc_group: "component_playbook"
            rc_number: 5009
            rc_message:
              "Redhat update_all or rcp_all patching failed.
              Below is the error:
              {{ update_rcp_result.stdout }}"

        - name: Failure - patches not installed
          ansible.builtin.set_fact:
            patch_status: 'failure'
            exec_message:
              "{{ exec_message }}
              Patching result:\n\n
              Patch installation FAILED, please perform manual patching.\n\n"

        - name: Send communication
          ansible.builtin.include_tasks: send_notification.yml

        - name: Remove lock file
          ansible.builtin.file:
            path:
              /etc/ansible/facts.d{{
              '' if lock_file_dir.changed else '/unix_patching.fact' }}
            state: absent

        - name: End the job for the host {{ inventory_hostname }}
          ansible.builtin.fail:
            msg: "Redhat update_all or rcp_all patching failed"
          when:
            - fail_on_error | bool
            - not teams_notification

        - name: Set continue_execution flag
          ansible.builtin.set_fact:
            continue_execution: false

# Nothing to do here, all packages are up to date
- name: Nothing to do here, all packages are up to date
  when:
    - update_rcp_result is not failed or
      (retry_update_rcp_result is defined and
      retry_update_rcp_result.rc == 0)
    - (not run_pre_patch_steps and
      (not update_rcp_result.changed or
      (retry_update_rcp_result is defined and
      'Nothing to do' in retry_update_rcp_result.stdout)))
      or (run_pre_patch_steps and
      'Nothing to do' in update_rcp_result.stdout)
  block:

    - name: Set returncode
      ansible.builtin.include_role:
        name: returncode
      vars:
        rc_success: true
        rc_message: "Nothing to do here, all packages are up to date"

    - name: Set exec_message
      ansible.builtin.set_fact:
        patch_status: 'nothing_to_do'
        exec_message:
          "{{ exec_message }}
          Patching result:\n\n
          Nothing to do here, all packages are up to date.\n\n"

- name: Patches installed successfully
  when:
    - patch_status != 'nothing_to_do'
    - update_rcp_result is not failed or
      (retry_update_rcp_result is defined and
      retry_update_rcp_result.rc == 0)
  block:

    - name: Set returncode
      ansible.builtin.include_role:
        name: returncode
      vars:
        rc_success: true
        rc_message: "Patches installed successfully"

    - name: Set exec_message
      ansible.builtin.set_fact:
        patch_status: 'success'
        exec_message:
          "{{ exec_message }}
          Patching result:\n\n
          Patches installed successfully.\n\n"
