---
- name: Install single/multiple package(s)
  block:

    - name: Install single/multiple package(s)
      community.general.zypper:
        name: "{{ item }}"
        state: present
        extra_args: '{{ extra_args_suse }}'
      register: patch_result
      loop: "{{ patch_name }}"
      async: "{{ async_value }}"
      poll: "{{ poll_value }}"

    - name: Set returncode
      ansible.builtin.include_role:
        name: returncode
      vars:
        rc_success: true

    - name: Set exec_message
      ansible.builtin.set_fact:
        patch_status: 'success'
        exec_message:
          "{{ exec_message }}
          Patching result:\n\n
          Patches installed successfully.\n\n"

  rescue:

    - name: Return code incase of Suse specific patch fails
      ansible.builtin.include_role:
        name: returncode
      vars:
        rc_support: "developer"
        rc_group: "component_playbook"
        rc_number: 5014
        rc_message: "Suse specific patching {{ patch_name }} failed."

    - name: Specific packages installation status
      ansible.builtin.set_fact:
        patch_status: 'failure'
        exec_message:
          "{{ exec_message }}
          Patching result:\n\n
          Patch installation FAILED, please perform patching manually.\n\n"

    - name: Send communication
      ansible.builtin.include_tasks: send_notification.yml

    - name: Remove lock file
      ansible.builtin.file:
        path:
          /etc/ansible/facts.d{{
          '' if lock_file_dir.changed else '/unix_patching.fact' }}
        state: absent

    - name: End the job for the host {{ inventory_hostname }}
      ansible.builtin.fail:
        msg: "Suse specific patching failed."
      when:
        - fail_on_error | bool
        - not teams_notification

    - name: Set continue_execution flag
      ansible.builtin.set_fact:
        continue_execution: false
