---
# ========== VARIABLES POR DEFECTO AWX_REGISTER ==========

# Valores por defecto para configuración AWX
awx_default_timeout: 30
awx_default_verify_ssl: false

# Variables de configuración por defecto
default_host_description: "Host registrado automáticamente por awx_register"

# Variables que se pueden sobrescribir desde el template AWX
# ambiente: ""     # Requerido desde template
# inventory: ""    # Requerido desde template  
# group: ""        # Requerido desde template

# Validaciones de formato
ip_regex: "^(?:[0-9]{1,3}\\.){3}[0-9]{1,3}$"
hostname_min_length: 1