---
- name: Update apt-get repo and cache
  block:

    - name: Update apt-get repo and cache
      ansible.builtin.apt:
        update_cache: true
        force_apt_get: true
        cache_valid_time: 3600
      register: apt_update_out
      async: "{{ async_value }}"
      poll: "{{ poll_value }}"

  rescue:

    - name: Return code incase of Ubuntu apt-get patch command fails
      ansible.builtin.include_role:
        name: returncode
      vars:
        rc_support: "developer"
        rc_group: "component_playbook"
        rc_number: 5015
        rc_message:
          "Ubuntu apt-get patching command failed."

    - name: Set exec_message
      ansible.builtin.set_fact:
        patch_status: 'failure'
        exec_message:
          "{{ exec_message }}
          Ubuntu apt-get patching command failed.\n\n"

    - name: Send communication
      ansible.builtin.include_tasks: send_notification.yml

    - name: Remove lock file
      ansible.builtin.file:
        path:
          /etc/ansible/facts.d{{
          '' if lock_file_dir.changed else '/unix_patching.fact' }}
        state: absent

    - name: End the job for the host {{ inventory_hostname }}
      ansible.builtin.fail:
        msg: "Ubuntu apt-get patching failed"
      when:
        - fail_on_error | bool
        - not teams_notification

    - name: Set continue_execution flag
      ansible.builtin.set_fact:
        continue_execution: false

- name: Upgrade all apt packages
  when: continue_execution
  block:

    - name: Upgrade all apt packages
      ansible.builtin.apt:
        upgrade: dist
        force_apt_get: true
      register: apt_upgrade_out
      async: "{{ async_value }}"
      poll: "{{ poll_value }}"

  rescue:

    - name: Return code incase of Ubuntu Upgrade patch command fails
      ansible.builtin.include_role:
        name: returncode
      vars:
        rc_support: "developer"
        rc_group: "component_playbook"
        rc_number: 5016
        rc_message:
          "Ubuntu Upgrade patching command failed."

    - name: Set exec_message
      ansible.builtin.set_fact:
        patch_status: 'failure'
        exec_message:
          "{{ exec_message }}
          Ubuntu Upgrade patching command failed.\n\n"

    - name: Send communication
      ansible.builtin.include_tasks: send_notification.yml

    - name: Remove lock file
      ansible.builtin.file:
        path:
          /etc/ansible/facts.d{{
          '' if lock_file_dir.changed else '/unix_patching.fact' }}
        state: absent

    - name: End the job for the host {{ inventory_hostname }}
      ansible.builtin.fail:
        msg: "Ubuntu Upgrade patching failed"
      when:
        - fail_on_error | bool
        - not teams_notification

    - name: Set continue_execution flag
      ansible.builtin.set_fact:
        continue_execution: false

- name: Patches installed successfully
  when:
    - not apt_upgrade_out.failed
    - apt_upgrade_out.changed
  block:

    - name: Set returncode
      ansible.builtin.include_role:
        name: returncode
      vars:
        rc_success: true
        rc_message: "Patches successfully installed"

    - name: Set exec_message
      ansible.builtin.set_fact:
        patch_status: 'success'
        exec_message:
          "{{ exec_message }}
          Patching result:\n\n
          Patches successfully installed.\n\n"

- name: Nothing to do here, all packages are up to date
  when:
    - not apt_upgrade_out.failed
    - not apt_upgrade_out.changed
  block:

    - name: Set returncode
      ansible.builtin.include_role:
        name: returncode
      vars:
        rc_success: true
        rc_message: "Nothing to do here, all packages are up to date"

    - name: Set exec_message
      ansible.builtin.set_fact:
        patch_status: 'nothing_to_do'
        exec_message:
          "{{ exec_message }}
          Patching result:\n\n
          Nothing to do here, all packages are up to date.\n\n"

- name: Failure - patches not installed
  ansible.builtin.set_fact:
    patch_status: 'failure'
    exec_message:
      "{{ exec_message }}
      Patching result:\n\n
      Patch installation FAILED, please perform manual patching.\n\n"
  when: apt_upgrade_out.failed
