---

- name: Run ICV role
  hosts: all
  gather_facts: false
  vars:
    send_email: false
    recipients: []
    smtp_host_ip: ''
    smtp_port: 25
    teams_notification: false
    channel_webhook_url: ''
    sender: "(Ansible Robot) ansible-robot@kyndryl.com"
  tasks:

    - name: Set link to documentation and asset
      ansible.builtin.include_role:
        name: returncode
        tasks_from: set_job_properties
      vars:
        asset_name: "Pre Patching Validation"
        documentation:
          default:
            "https://github.kyndryl.net/Continuous-Engineering/ansible_collection_patching_unix"

    - name: Run ICV role
      ansible.builtin.include_role:
        name: ansible_role_input_control_validate
      vars:
        icv_variable_descriptor: "pre_patching_validation.json"
        icv_playbook_dir_path_level: 1

    - name: Input validation failed
      when: returncode != "0"
      block:

        - name: Include communication role - input validation failure
          when:
            teams_notification or send_email
          ansible.builtin.include_role:
            name: communication
            tasks_from: validation_failure_communication.yml

        - name: End the job
          ansible.builtin.fail:
            msg: "Input validation failed"

- name: Prepare SFS upload environment
  hosts: localhost
  connection: local
  gather_facts: false
  vars:
    backup_to_jumphost: false
    teams_notification: false
    channel_webhook_url: ''
    sfs_upload: false
  tasks:
    - name: Prepare
      ansible.builtin.include_role:
        name: sfs_upload
      vars:
        sfs_upload_stage: "prepare"
        output_dir: "/tmp/gts-ansible/patching"
      when:
        backup_to_jumphost or
        (teams_notification and channel_webhook_url | length) or
        (send_email and recipients | length) or
        sfs_upload

- name: Linux pre patching
  hosts: all
  gather_facts: false
  become: true
  vars:
    send_email: false
    teams_notification: false
    recipients: []
    channel_webhook_url: ''
    sfs_upload: false
    patching_pre_req_validation: false
    continue_execution: true
    fail_on_error: true
    attach_config_data: false
  tasks:

    - name: Set link to documentation and asset
      ansible.builtin.include_role:
        name: returncode
        tasks_from: set_job_properties
      vars:
        asset_name: "Pre Patching Validation"
        documentation:
          default:
            "https://github.kyndryl.net/Continuous-Engineering/ansible_collection_patching_unix"

    - name: Initialize exec_message
      ansible.builtin.set_fact:
        exec_message:
          "Hostname: {{ inventory_hostname }}\n\n"
      when:
        (send_email and recipients | length) or
        sfs_upload

    - name: Include pre_patching_validation role
      ansible.builtin.include_role:
        name: pre_patching_validation

    - name: Set current host for MS team notification
      ansible.builtin.set_fact:
        current_host:
          "{{ inventory_hostname }}"

    - name: Remove lock file
      when: gathered_facts.unreachable is not defined
      ansible.builtin.file:
        path:
          /etc/ansible/facts.d{{
          '' if lock_file_dir.changed else '/unix_patching.fact' }}
        state: absent

    - name: Include communication role
      when:
        teams_notification or
        send_email or
        sfs_upload
      ansible.builtin.include_role:
        name: communication
        tasks_from: linux_pre_patching_communication.yml
      vars:
        communication_type: "individual"

    - name: Include communication role
      when:
        - (teams_notification or send_email or sfs_upload)
        - inventory_hostname == ansible_play_hosts[-1]
      ansible.builtin.include_role:
        name: communication
        tasks_from: linux_pre_patching_communication.yml
      vars:
        communication_type: "consolidated"

    - name: End the job
      ansible.builtin.fail:
        msg: "Pre patching validation failed"
      when:
        - fail_on_error | bool
        - not continue_execution
